### PR TITLE
PR for the support for PHP 5.4 and 7.0

### PR DESCRIPTION
**Pull request by jmontoyaa**
See https://github.com/essence/essence/issues/122

### CODE REVIEW

**Comment by felixgirault** [comment]
Thank you!

**Comment by ywarnier** [comment]
It would be great if you could tag a version (like 2.5.3 or something like that) with that change so we can depend on it through Composer and not on the branch (please :-))

**Comment by felixgirault** [comment]
I already did ;) https://github.com/essence/essence/issues/122#issuecomment-240340759
Sorry I forgot to mention it here.

**Comment by ywarnier** [comment]
Ups, great, thank you!

**Pull request merged**
